# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0vRaH6mqLhVzXnqAelIC0u0AJiwtaM6
"""
import gradio as gr
from chatbot import*
# creating Gradio graphical interface
with gr.Blocks() as demo:
    gr.Markdown("### شات بوت للإجابة عن الأحكام الشرعية للصلاة")
    gr.Markdown("💡 تحذير هذاالشات بوت للأغراض التعليمية, إذا أردت معرفة الأحكام الشرعية اسأل أحد المشايخ الموثوقين, قال تعالى: (فاسألوا أهل الذكر إن كنتم لاتعلمون)!")
    chat_history = gr.State([])
    with gr.Row():
        with gr.Column():
            question = gr.Textbox(placeholder="اسألني سؤالاً عن أحكام الصلاة ...")
            send_button = gr.Button("إرسال")
        with gr.Column():
            answer = gr.Textbox(interactive=False)

    send_button.click(fn=find_best_answer, inputs=[question, chat_history], outputs=[answer, chat_history])

# running the app
demo.launch(share=True)